//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebtDiary.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DebtDiary.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can log in now.
        /// </summary>
        public static string AccountCreatedSubtitle {
            get {
                return ResourceManager.GetString("AccountCreatedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created.
        /// </summary>
        public static string AccountCreatedTitle {
            get {
                return ResourceManager.GetString("AccountCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a debtor.
        /// </summary>
        public static string AddADebtor {
            get {
                return ResourceManager.GetString("AddADebtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition date.
        /// </summary>
        public static string AdditionDate {
            get {
                return ResourceManager.GetString("AdditionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new debtor.
        /// </summary>
        public static string AddNewDebtor {
            get {
                return ResourceManager.GetString("AddNewDebtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt diary.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaworski.
        /// </summary>
        public static string AuthorString {
            get {
                return ResourceManager.GetString("AuthorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt course.
        /// </summary>
        public static string DebtCourse {
            get {
                return ResourceManager.GetString("DebtCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owes you.
        /// </summary>
        public static string DebtFemale {
            get {
                return ResourceManager.GetString("DebtFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owes you.
        /// </summary>
        public static string DebtMale {
            get {
                return ResourceManager.GetString("DebtMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be moved to the summary now.
        /// </summary>
        public static string DebtorDeletedSubtitle {
            get {
                return ResourceManager.GetString("DebtorDeletedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This debtor has been deleted.
        /// </summary>
        public static string DebtorDeletedTitle {
            get {
                return ResourceManager.GetString("DebtorDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check this changes now.
        /// </summary>
        public static string DebtorEditedSubtitle {
            get {
                return ResourceManager.GetString("DebtorEditedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor has been edited.
        /// </summary>
        public static string DebtorEditedTitle {
            get {
                return ResourceManager.GetString("DebtorEditedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This debtor has been already added.
        /// </summary>
        public static string DebtorExist {
            get {
                return ResourceManager.GetString("DebtorExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBTORS.
        /// </summary>
        public static string Debtors {
            get {
                return ResourceManager.GetString("Debtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts course.
        /// </summary>
        public static string DebtsCourse {
            get {
                return ResourceManager.GetString("DebtsCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete debtor.
        /// </summary>
        public static string DeleteDebtor {
            get {
                return ResourceManager.GetString("DeleteDebtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered passwords are not the same.
        /// </summary>
        public static string DifferentPasswords {
            get {
                return ResourceManager.GetString("DifferentPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit debtor.
        /// </summary>
        public static string EditDebtor {
            get {
                return ResourceManager.GetString("EditDebtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter current password.
        /// </summary>
        public static string EmptyCurrentPassword {
            get {
                return ResourceManager.GetString("EmptyCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        public static string EmptyDescription {
            get {
                return ResourceManager.GetString("EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail address.
        /// </summary>
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name.
        /// </summary>
        public static string EmptyFirstName {
            get {
                return ResourceManager.GetString("EmptyFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        public static string EmptyLastName {
            get {
                return ResourceManager.GetString("EmptyLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string EmptyNewPassword {
            get {
                return ResourceManager.GetString("EmptyNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string EmptyRepeatedNewPassword {
            get {
                return ResourceManager.GetString("EmptyRepeatedNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string EmptyRepeatedPassword {
            get {
                return ResourceManager.GetString("EmptyRepeatedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        public static string EmptyUsername {
            get {
                return ResourceManager.GetString("EmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount.
        /// </summary>
        public static string EmptyValue {
            get {
                return ResourceManager.GetString("EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect current password.
        /// </summary>
        public static string IncorrectCurrentPassword {
            get {
                return ResourceManager.GetString("IncorrectCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect date.
        /// </summary>
        public static string IncorrectDate {
            get {
                return ResourceManager.GetString("IncorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect description.
        /// </summary>
        public static string IncorrectDescription {
            get {
                return ResourceManager.GetString("IncorrectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect e-mail address.
        /// </summary>
        public static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect first name.
        /// </summary>
        public static string IncorrectFirstName {
            get {
                return ResourceManager.GetString("IncorrectFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect last name.
        /// </summary>
        public static string IncorrectLastName {
            get {
                return ResourceManager.GetString("IncorrectLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username.
        /// </summary>
        public static string IncorrectUsername {
            get {
                return ResourceManager.GetString("IncorrectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect amount.
        /// </summary>
        public static string IncorrectValue {
            get {
                return ResourceManager.GetString("IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last operation.
        /// </summary>
        public static string LastOperation {
            get {
                return ResourceManager.GetString("LastOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last operations.
        /// </summary>
        public static string LastOperations {
            get {
                return ResourceManager.GetString("LastOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string Loan {
            get {
                return ResourceManager.GetString("Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need a place to store your debts information?.
        /// </summary>
        public static string LoginPageSubtitle {
            get {
                return ResourceManager.GetString("LoginPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You owe her.
        /// </summary>
        public static string MinusDebtFemaleToFemale {
            get {
                return ResourceManager.GetString("MinusDebtFemaleToFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You owe him.
        /// </summary>
        public static string MinusDebtFemaleToMale {
            get {
                return ResourceManager.GetString("MinusDebtFemaleToMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You owe her.
        /// </summary>
        public static string MinusDebtMaleToFemale {
            get {
                return ResourceManager.GetString("MinusDebtMaleToFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You owe him.
        /// </summary>
        public static string MinusDebtMaleToMale {
            get {
                return ResourceManager.GetString("MinusDebtMaleToMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter positive amount.
        /// </summary>
        public static string NegativeNumber {
            get {
                return ResourceManager.GetString("NegativeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be moved to their subpage now.
        /// </summary>
        public static string NewDebtorAddedSubtitle {
            get {
                return ResourceManager.GetString("NewDebtorAddedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New debtor has been added.
        /// </summary>
        public static string NewDebtorAddedTitle {
            get {
                return ResourceManager.GetString("NewDebtorAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no debtors added.
        /// </summary>
        public static string NoDebtorsAdded {
            get {
                return ResourceManager.GetString("NoDebtorsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection.
        /// </summary>
        public static string NoInternetConnectionSubtitle {
            get {
                return ResourceManager.GetString("NoInternetConnectionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the database.
        /// </summary>
        public static string NoInternetConnectionTitle {
            get {
                return ResourceManager.GetString("NoInternetConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no operations added.
        /// </summary>
        public static string NoOperationsAdded {
            get {
                return ResourceManager.GetString("NoOperationsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of debtors.
        /// </summary>
        public static string NumberOfDebtors {
            get {
                return ResourceManager.GetString("NumberOfDebtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of operations.
        /// </summary>
        public static string NumberOfOperations {
            get {
                return ResourceManager.GetString("NumberOfOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change it again or edit your profile.
        /// </summary>
        public static string PasswordChangedSubtitle {
            get {
                return ResourceManager.GetString("PasswordChangedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string PasswordChangedTitle {
            get {
                return ResourceManager.GetString("PasswordChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should have 8 characters.
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She.
        /// </summary>
        public static string PersonFemale {
            get {
                return ResourceManager.GetString("PersonFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He.
        /// </summary>
        public static string PersonMale {
            get {
                return ResourceManager.GetString("PersonMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit it again or change your password.
        /// </summary>
        public static string ProfileUpdatedSubtitle {
            get {
                return ResourceManager.GetString("ProfileUpdatedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated.
        /// </summary>
        public static string ProfileUpdatedTitle {
            get {
                return ResourceManager.GetString("ProfileUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string RegisterPageSubtitle {
            get {
                return ResourceManager.GetString("RegisterPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repayment.
        /// </summary>
        public static string Repayment {
            get {
                return ResourceManager.GetString("Repayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of debts.
        /// </summary>
        public static string SumOfDebts {
            get {
                return ResourceManager.GetString("SumOfDebts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is already taken.
        /// </summary>
        public static string TakenEmail {
            get {
                return ResourceManager.GetString("TakenEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken.
        /// </summary>
        public static string TakenUsername {
            get {
                return ResourceManager.GetString("TakenUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is unselected.
        /// </summary>
        public static string UnselectedGender {
            get {
                return ResourceManager.GetString("UnselectedGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who borrowed?.
        /// </summary>
        public static string WhoBorrowed {
            get {
                return ResourceManager.GetString("WhoBorrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who repayed?.
        /// </summary>
        public static string WhoRepayed {
            get {
                return ResourceManager.GetString("WhoRepayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
    }
}
